# Generated by Django 5.2.7 on 2025-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_created_by_author_status_book_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
