# Generated by Django 5.2.7 on 2025-12-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_forwarded_status_orderitem_forwarded_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='forwarded_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='forwarded_to',
        ),
    ]
