# Generated by Django 5.2.7 on 2025-12-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='forwarded',
        ),
    ]
