# Generated by Django 5.2.7 on 2026-01-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/orders/'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/suborders/'),
        ),
    ]
